skip-changelog:
  - any: [ '.github/**/*', '.gitignore', 'Jenkinsfile', '.mvn/**/*', '.settings/*', '.sonarcloud.properties' ]

dependencies:
  - any: [ 'pom.xml' ]

documentation:
  - any: [ '*.adoc', '**/*.html', '**/*.png', 'LICENSE' ]

test:
  - any: [ ' src/test/**/*' ]
